### PR TITLE
[ Fix ] Exit with correct code after failed command

### LINKED ISSUE #38: Failing test doesn't prevent git push
Hi, I'm experiencing an issue where a failed unit test isn't preventing a push.

It's also worth noting that I get the two following lines before the tests start running:

```console
stty: stdin isn't a terminal
stty: stdin isn't a terminal
```

Here's my `whisky.json` file contents:

```json
{
  "disabled": [],
  "hooks": {
    "pre-commit": [
      "./vendor/bin/pint"
    ],
    "pre-push": [
      "php artisan test --parallel",
      "./vendor/bin/phpstan analyse"
    ],
    "post-checkout": [
      "composer install",
      "php artisan optimize:clear"
    ]
  }
}

```

And here's the command line output:

```console
11:03:40 in vapour on  feature/bottling-module [⇡]
➜ git push
stty: stdin isn't a terminal
stty: stdin isn't a terminal
ParaTest v7.2.0 upon PHPUnit 10.2.2 by Sebastian Bergmann and contributors.

Processes:     8
Runtime:       PHP 8.2.5
Configuration: /Users/stephenhamilton/Sites/vapour/phpunit.xml

...............................................................  63 / 416 ( 15%)
............................................................... 126 / 416 ( 30%)
............................................................... 189 / 416 ( 45%)
..........................................................I.... 252 / 416 ( 60%)
.......I.I..................................................... 315 / 416 ( 75%)
................................F.............................. 378 / 416 ( 90%)
......................................                          416 / 416 (100%)

Time: 01:25.270, Memory: 62.50 MB

There was 1 failure:

1) Tests\Feature\Tasks\SampleTest::test_completing_sample_task
Failed asserting that 13.1 matches expected 13.100000000000001.

/Users/stephenhamilton/Sites/vapour/tests/Feature/Tasks/SampleTest.php:184
/Users/stephenhamilton/Sites/vapour/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:174

FAILURES!
Tests: 416, Assertions: 57498, Failures: 1, Incomplete: 3.
Note: Using configuration file /Users/stephenhamilton/Sites/vapour/phpstan.neon.
 753/753 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%



 [OK] No errors


Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 623 bytes | 623.00 KiB/s, done.
Total 6 (delta 4), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To github.com:speysidelabs/vapour.git
   8dbae0ea..054f9095  feature/bottling-module -> feature/bottling-module
```

### PR DESCRIPTION
**Pull request by gpibarra**
Resolves #38

# Step to reproduce

```bash
# clone repo
git clone https://github.com/ProjektGopher/whisky.git
cd whisky
# install dependences
composer install

# install hook of this repo (linter-pint, stan and test)
php whisky install -n

touch .env
# or in Windows
# echo.  > .env
```

# Force test failure

File: ./tests/Unit/ExampleTest.php

```diff
<?php

test('example', function () {
-    expect(true)->toBeTrue();
+    expect(false)->toBeTrue();
});
```

# Check fails test

```bash
composer test
```

# Prevent commits if has errors

File: whisky.json
```diff
{
    "disabled": [],
    "hooks": {
        "pre-commit": [
-            "composer lint -- --test"
+            "composer test"
        ],
        "pre-push": [
            "composer lint -- --test",
            "composer stan",
            "composer types",
            "composer test"
        ]
    }
}
```

# Try commit

```bash
git add .
git commit -m "test"
```

This works correctly, ie: cannot commit if there are errors

## Multiples commands in hook

File: whisky.json
```diff
{
    "disabled": [],
    "hooks": {
        "pre-commit": [
+            "composer lint -- --test",
            "composer test"
        ],
        "pre-push": [
            "composer lint -- --test",
            "composer stan",
            "composer types",
            "composer test"
        ]
    }
}
```

And

```bash
git add .
git commit -m "test"
```

This works correctly, ie: cannot commit if there are errors

## Multiples commands in hook depends of order

File: whisky.json

```diff
{
    "disabled": [],
    "hooks": {
        "pre-commit": [
-            "composer lint -- --test"
-            "composer test"
+            "composer test",
+            "composer lint -- --test"
        ],
        "pre-push": [
            "composer lint -- --test",
            "composer stan",
            "composer types",
            "composer test"
        ]
    }
}
```

And

```bash
git add .
git commit -m "test"
```

This does not work, the commit is done even if there are errors

# Revert last commit
```bash
git reset --soft HEAD~1
```

### CODE REVIEW

File: bin/run-hook [hunk 1]
```diff
@@ -16,6 +16,12 @@ SCRIPTS=$($bin scripts "$hook")
 IFS=$'\n'
 
 # Run each script
+exit_code=0
 for SCRIPT in $SCRIPTS; do
     eval "$SCRIPT"
+    last_exit_code=$?
+    if [ $last_exit_code -ne 0 ]; then
+        exit_code=$last_exit_code
+        exit $exit_code
```
Comment (ProjektGopher) [inline bin/run-hook:25]: Would this line need to be outside the loop?

Comment (ProjektGopher) [reply bin/run-hook]: confirmed

**Comment by ProjektGopher** [comment]
@gpibarra a useful trick for testing out hooks without having to make extra commits that have to then get reset is to run `git hook run pre-commit`

**Review by ProjektGopher — APPROVED** [review]

File: bin/run-hook (hunk 1 above)
Comment (ProjektGopher) [reply bin/run-hook]: I opted for the second, but I wonder if there should be a 'fail fast' option.
